COLUMNS:
  VendorID: Int64
  tpep_pickup_datetime: Utf8
  tpep_dropoff_datetime: Utf8
  passenger_count: Float64
  trip_distance: Float64
  RatecodeID: Float64
  store_and_fwd_flag: Utf8
  PULocationID: Int64
  DOLocationID: Int64
  payment_type: Int64
  fare_amount: Float64
  extra: Float64
  mta_tax: Float64
  tip_amount: Float64
  tolls_amount: Float64
  improvement_surcharge: Float64
  total_amount: Float64
  congestion_surcharge: Float64
  airport_fee: Float64

TARGET_COLUMN:
  name: tip_amount
  type: Float64
